### Site info:
title: Untwine
tagline: 
author: Untwine
email: unknot1@gmail.com
description: "" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: ""
url: "http://www.untwine.ru" # the base hostname & protocol for your site
permalink: /:title/

### Personal info and site tools info:
twitter_username:
github_username:
disqus_shortname:
favicon: "/images/favicon.ico"
aboutme:
aboutme_photo: # your photo.


### Site setting:
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "ru" # blog sidebar language set, only include: English(en) and Chinese (cn)

locales:
    en:
      Aboutme: "About Me"
      Archives: "Archives"
      Blogroll: "Blogroll"
      Categories: "Categories"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Recent Posts"
      Tags: "Tags"
      Previous: "Older"
      Next: "Newer"
      PostedInCategories: "Posted in"
      Taggedwith: "and tagged"  
      PostDate: "on "
    ru:
      Aboutme: "Обо мне"
      Archives: "Архив"
      Blogroll: "Блогролл"
      Categories: "Категории"
      Copyright_Notice: "Копирайт"
      Recent_Posts: "Последние записи"
      Tags: "Тэги"
      Previous: "Предыдущая запись"
      Next: "Следующая запись"
      PostedInCategories: "Размещено в"
      Taggedwith: "с тэгами"  
      PostDate: " "


### your Blogroll info, only name can shown on the page.


### Build settings
markdown: kramdown
highlighter: rouge
paginate: 5
